steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="REBEL_ENV" > /workspace/.env

        # Example usage of the config file
        cat /workspace/.env
        
        gcloud app deploy --quiet


options:
  logging: 'CLOUD_LOGGING_ONLY'
