steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  env:
      - GOOGLE_CLOUD_PROJECT=${_VAL1}
      - GOOGLE_CLOUD_FIRESTORE_DB=${_VAL2}
      - GOOGLE_CLOUD_CREDENTIALS=${_VAL3}

options:
  logging: 'CLOUD_LOGGING_ONLY'
